=== GUIForWeb/Manager/setting.dtd
<!ELEMENT settings ((directories|values|setting)+)>
<!ELEMENT directories ((directory)+)>
<!ELEMENT directory (#PCDATA)>
<!ATTLIST directory name CDATA #REQUIRED>
<!ELEMENT values ((value|valuez)+)>
<!ELEMENT valuez ((value)+)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value name CDATA #REQUIRED>
<!ELEMENT setting (#PCDATA)>
<!ATTLIST setting name CDATA #REQUIRED>

=== GUIForWeb/Manager/setting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setting SYSTEM "setting.dtd">
<settings>
	<directories>
		<directory name="server">/opt/tomcat</directory>
		<directory name="sqlite">/opt/home</directory>
		<directory name="storage">/opt/sqlite</directory>
	</directories>
	<values>
		<value name="a">A</value>
		<value name="b">B</value>
		<value name="c">C</value>
		<valuez>
			<value name="aa">AA</value>
			<value name="bb">BB</value>
			<value name="cc">CC</value>
		</valuez>
		<valuezz>
			<value name="dd">DD</value>
			<value name="ee">EE</value>
			<value name="ff">FF</value>
		</valuezz>
	</values>
	<setting name="s">S</setting>
	<setting name="ss">SS</setting>
</settings>
